apiVersion: karpenter.k8s.aws/v1beta1
kind: NodePool
metadata:
  name: api-nodepool
spec:
  template:
    metadata:
      labels:
        app: api
      annotations:
        karpenter.k8s.aws/instance-profile: "KarpenterNodeInstanceProfile-eks" # Change this if needed
    spec:
      taints:
        - key: dedicated
          value: api
          effect: NoSchedule
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: In
          values: ["5"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: ["large", "xlarge"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b"] # Change based on your region
        - key: "karpenter.k8s.aws/compute-optimized"
          operator: Exists
      nodeClassRef:
        name: default
  limits:
    cpu: "1000"
    memory: "1000Gi"
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 30m # Nodes expire if idle for 30 minutes
